export const skillIcons = {
  "ChromaDB": "/icons/chromadb.svg",
  "Chroma": "/icons/chromadb.svg",
  "LlamaIndex": "/icons/llamaindex.png",
  "LangChain": "/icons/langchain.svg",
  "OpenCV": "/icons/opencv.svg",
  "YOLO": "/icons/yolo.svg",
  "YOLO v11": "/icons/yolo.svg",
  "MediaPipe": "/icons/mediapipe.svg",
  "ONNX": "/icons/onnx.svg",
  "PyTorch": "/icons/pytorch.svg",
  "TensorFlow": "/icons/tensorflow.svg",
  "Keras": "/icons/keras.svg",
  "Pandas": "/icons/pandas.svg",
  "NumPy": "/icons/numpy.svg",
  "Scikit-learn": "/icons/scikitlearn.svg",
  "Scikit-Learn": "/icons/scikitlearn.svg",
  "Hugging Face": "/icons/huggingface.svg",
  "Python": "/icons/python.svg",
  "C++": "/icons/cplusplus.svg",
  "Docker": "/icons/docker.svg",
  "Linux": "/icons/linux.svg",
  "Next.js": "/icons/nextjs.svg",
  "MongoDB": "/icons/mongodb.svg",
  "PostgreSQL": "/icons/postgresql.svg",
  "Git": "/icons/git.svg",
  "uv": "/icons/uv.svg",
  "FastAPI": "/icons/fastapi.svg",
  "Flask": "/icons/flask.svg",
  "React": "/icons/react.svg"
};

